# Advent of Code 2024

## Day 1

In [3]:
import aoc
aoc.read_input("cookie.txt", "input_2024", 2024, 1)

### Puzzle 1

In [33]:
with open("input_2024/example1.txt") as f:
    line_ints_list = []
    for line in f:
        line_ints = [int(val) for val in line.strip().split()]
        line_ints_list.append(line_ints)

In [34]:
cols = [v for v in zip(*line_ints_list)]
left_col = sorted(cols[0])
right_col = sorted(cols[1])
sum([abs(left - right) for left, right in zip(left_col, right_col)])

11

### Puzzle 2

In [35]:
left_col_set = set(left_col)
right_col_count = {num:right_col.count(num) for num in left_col_set }
similarities = [num * right_col_count[num] for num in left_col]
sum(similarities)

31

## Day 2

In [51]:
import aoc
aoc.read_input("cookie.txt", "input_2024", 2024, 2)

In [50]:
import numpy as np

array = np.loadtxt("input_2024/example2.txt", dtype=int)
array

array([[7, 6, 4, 2, 1],
       [1, 2, 7, 8, 9],
       [9, 7, 6, 2, 1],
       [1, 3, 2, 4, 5],
       [8, 6, 4, 4, 1],
       [1, 3, 6, 7, 9]])

In [66]:
diffs = np.diff(array)
diffs

array([[-1, -2, -2, -1],
       [ 1,  5,  1,  1],
       [-2, -1, -4, -1],
       [ 2, -1,  2,  1],
       [-2, -2,  0, -3],
       [ 2,  3,  1,  2]])

In [69]:
diffs[0]

array([-1, -2, -2, -1])

In [73]:
np.all(diffs[1] > 0)

np.True_

In [ ]:
safecout = 0
for report in diffs:
    if np.all(report > 0) and np.max(report) <= 3:
        print("pos", report)
        safecount += 1
    elif np.all(report < 0) and np.min(report) >= -3:
        print("neg", report)
        safecount += 1
safecount

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2677547388.py, line 4)

In [ ]:
safe_count = 0
for report in array:
    for i, level in enumerate(report):
        if 

array([[3, 4],
       [4, 3],
       [2, 5],
       [1, 3],
       [3, 9],
       [3, 3]])

In [47]:
array.T

array([[3, 4, 2, 1, 3, 3],
       [4, 3, 5, 3, 9, 3]])

In [42]:
A

array([3, 4, 2, 1, 3, 3])

In [43]:
B

array([4, 3, 5, 3, 9, 3])